test : 
	python main.py < ../io/sample.in.1 > output_1.txt
	python main.py < ../io/sample.in.2 > output_2.txt
	python main.py < ../io/sample.in.3 > output_3.txt
	python main.py < ../io/sample.in.4 > output_4.txt